### ISSUE TITLE
Missing argument for parameter 'router' in call

### ISSUE THREAD

**Issue by zephoon** [codytwinton/SwiftyVIPER#3]
Thanks for your SwiftyViper.
When i make a new viper module and it display two errors, `Missing argument for parameter 'router' in call ` and `value of type 'testRouter' has no member 'view'` in my `testConfigurator.swift` file.

**Comment by codytwinton** [comment]
@zeffon - Sorry to hear you're having issues. Few questions:
1. Are you using Cocoapods or manual installation for the standard VIPER protocols?
2. Did you create a Module and a Test Module or merely a Module?

Also, if you can upload a screen shot, that can help to resolve this.

**Comment by codytwinton** [comment]
@zeffon - I've made a few updates to the Module templates and the `README.md` file. Let me know if this resolves the problem.

**Comment by codytwinton** [comment]
@zeffon I'm going to close this issue for now. If you run into other errors with the project, feel free to open up another issue.

**Comment by zeffon** [comment]
Thanks for your message.

When I pod install, my console display red warnings "[!] Unable to find a specification for SwiftyVIPER"

This is the content of my Podfile in a new blank project below:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testViper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testViper
pod 'SwiftyVIPER'
end
```

**Comment by zephoon** [comment]
Thanks for your reply. I install SwiftyViper via Cocopods.

<img width="274" alt="screen shot 2016-11-15 at 17 31 12" src="https://cloud.githubusercontent.com/assets/4590967/20300320/a4f5e1be-ab59-11e6-8d7b-e9e4d97d3788.png">
<img width="1075" alt="screen shot 2016-11-15 at 17 30 58" src="https://cloud.githubusercontent.com/assets/4590967/20300322/a65a008a-ab59-11e6-97f8-ae398a398bb2.png">

**Comment by codytwinton** [comment]
@zeffon - This configurator class is new to me. With the VIPER templates included, the `ssModule()` should setup everything for you.

**Comment by zephoon** [comment]
Thanks, I check myself now.

**Comment by zephoon** [comment]
@codytwinton I am so sorry because it is my mistake. 
I use two viper template generator and other one is `ViperTemplate` in the same time. I has uninstalled  `ViperTemplate` and reinstall your `SwiftyViper` so it can work.
I have a suggestion that  generating viper templates using RxSwift maybe more nice for your `SwiftyViper`.

**Comment by codytwinton** [comment]
@zeffon That's awesome! I'm not currently using `RxSwift` and so I'm fairly unfamiliar with it. But I'm open to pull requests. Just create a new template and label it something like `Module Rx`.
