### ISSUE TITLE
[!] Unable to find a specification for `SwiftyVIPER`

### ISSUE THREAD

**Issue by zephoon** [codytwinton/SwiftyVIPER#4]
When I pod install, my console display red warnings "[!] Unable to find a specification for `SwiftyVIPER`"

This is the content of my  Podfile in a new blank project below:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testViper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testViper
pod 'SwiftyVIPER'
end
```

**Comment by codytwinton** [comment]
@zeffon - I'm assuming you're resolved this issue since you closed it. Let me know if you need any help.
