### ISSUE TITLE
Carthage installation error

### ISSUE THREAD

**Issue by litoarias** [codytwinton/SwiftyVIPER#5]
Hi guys, good idea 😀  for VIPER generator

But the version of Carthage it's not available.. 

> github "codytwinton/SwiftyVIPER" ~> 4.0

> No available version for github "codytwinton/SwiftyVIPER" satisfies the requirement: ~> 4.0.0

Without version 

> The following build commands failed:
	PhaseScriptExecution Swift\ Lint /Users/Lito/Library/Developer/Xcode/DerivedData/SwiftyVIPER-ewlkpssthmgrxzeyuoczepotiwud/Build/Intermediates/SwiftyVIPER.build/Release-appletvos/SwiftyVIPERtvOS.build/Script-6AA354C81E1783A500FB46AA.sh
(1 failure)

Last release it's **1.2.3**? This version it's availavable.. not **4.0**..

Thnxs

**Comment by codytwinton** [comment]
@litoarias - Good catch, thanks! Updated the `README.md` file

**Comment by litoarias** [comment]
@codytwinton installation via Carthage not run:
Following this error:

![captura de pantalla 2017-01-14 a las 21 58 41](https://cloud.githubusercontent.com/assets/7962872/21958080/36789f26-daa5-11e6-8bd1-3e65f81af161.png)

**Comment by codytwinton** [comment]
@litoarias - I've done a few updates to the Xcode project, which should resolve your issue, based on the errors I'm seeing.

**Comment by litoarias** [comment]
@codytwinton Thank you for your interest, throughout the day I will try it .. 😀

**Comment by litoarias** [comment]
The project run perfect via Carthage 🎉🎉🎉 .. Thnxs for your interest

**Comment by codytwinton** [comment]
@litoarias - Glad to hear! 🎉
